export const ADMIN_SIGN_IN_REQUEST = 'ADMIN_SIGN_IN_REQUEST';
export const ADMIN_SIGN_IN_SUCCESS = 'ADMIN_SIGN_IN_SUCCESS';
export const ADMIN_SIGN_IN_ERROR = 'ADMIN_SIGN_IN_ERROR';

export const ADMIN_SIGN_OUT_REQUEST = 'ADMIN_SIGN_OUT_REQUEST';
export const ADMIN_SIGN_OUT_SUCCESS = 'ADMIN_SIGN_OUT_SUCCESS';
export const ADMIN_SIGN_OUT_ERROR = 'ADMIN_SIGN_OUT_ERROR';

export const ADMIN_FORGOT_PASSWORD_REQUEST = 'ADMIN_FORGOT_PASSWORD_REQUEST';
export const ADMIN_FORGOT_PASSWORD_SUCCESS = 'ADMIN_FORGOT_PASSWORD_SUCCESS';
export const ADMIN_FORGOT_PASSWORD_ERROR = 'ADMIN_FORGOT_PASSWORD_ERROR';

export const ADMIN_CHECK_TOKEN = 'ADMIN_CHECK_TOKEN';
