export const ADMIN_MEDIA_FETCH_REQUEST = 'ADMIN_MEDIA_FETCH_REQUEST';
export const ADMIN_MEDIA_FETCH_SUCCESS = 'ADMIN_MEDIA_FETCH_SUCCESS';
export const ADMIN_MEDIA_FETCH_ERROR = 'ADMIN_MEDIA_FETCH_ERROR';

export const ADMIN_MEDIA_UPLOAD_REQUEST = 'ADMIN_MEDIA_UPLOAD_REQUEST';
export const ADMIN_MEDIA_UPLOAD_SUCCESS = 'ADMIN_MEDIA_UPLOAD_SUCCESS';
export const ADMIN_MEDIA_UPLOAD_ERROR = 'ADMIN_MEDIA_UPLOAD_ERROR';

export const ADMIN_MEDIA_DELETE_REQUEST = 'ADMIN_MEDIA_DELETE_REQUEST';
export const ADMIN_MEDIA_DELETE_SUCCESS = 'ADMIN_MEDIA_DELETE_SUCCESS';
export const ADMIN_MEDIA_DELETE_ERROR = 'ADMIN_MEDIA_DELETE_ERROR';

export const ADMIN_MEDIA_ALT_CHANGE_REQUEST = 'ADMIN_MEDIA_ALT_CHANGE_REQUEST';
export const ADMIN_MEDIA_ALT_CHANGE_SUCCESS = 'ADMIN_MEDIA_ALT_CHANGE_SUCCESS';
export const ADMIN_MEDIA_ALT_CHANGE_ERROR = 'ADMIN_MEDIA_ALT_CHANGE_ERROR';
