export const ADMIN_RESET_PASSWORD_CHECK_TOKEN_REQUEST = 'ADMIN_RESET_PASSWORD_CHECK_TOKEN_REQUEST';
export const ADMIN_RESET_PASSWORD_CHECK_TOKEN_SUCCESS = 'ADMIN_RESET_PASSWORD_CHECK_TOKEN_SUCCESS';
export const ADMIN_RESET_PASSWORD_CHECK_TOKEN_ERROR = 'ADMIN_RESET_PASSWORD_CHECK_TOKEN_ERROR';

export const ADMIN_SET_PASSWORD_REQUEST = 'ADMIN_SET_PASSWORD_REQUEST';
export const ADMIN_SET_PASSWORD_SUCCESS = 'ADMIN_SET_PASSWORD_SUCCESS';
export const ADMIN_SET_PASSWORD_ERROR = 'ADMIN_SET_PASSWORD_ERROR';
